c_compiler:            # [osx] # [x86]
  - clang              # [osx] # [x86]
c_compiler_version:    # [osx] # [x86]
  - 9                  # [osx] # [x86]
cxx_compiler:          # [osx] # [x86]
  - clangxx            # [osx] # [x86]
cxx_compiler_version:  # [osx] # [x86]
  - 9                  # [osx] # [x86]
c_compiler:            # [osx] #[arm64]
  - clang              # [osx] #[arm64]
c_compiler_version:    # [osx] #[arm64]
  - 16                  # [osx] #[arm64]
cxx_compiler:          # [osx] #[arm64]
  - clangxx            # [osx] #[arm64]
cxx_compiler_version:  # [osx] #[arm64]
  - 16                  # [osx] #[arm64]
